name: VM Nightly
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/vm

defaults:
  run:
    working-directory: packages/vm

jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # The job is meant to run with a fresh lock file
      # to detect any possible issues with new dep versions.
      - run: rm package-lock.json
        working-directory: ${{github.workspace}}

      - run: npm i
        working-directory: ${{github.workspace}}